[tool.poetry]
name = "EyeTrackVR"
version = "0.2"
description = "Opensource, affordable VR eye tracker for VRChat"
authors = ["RedHawk989"]
license = "LICENSE: Babble Software Distribution License 1.0"
repository = "https://github.com/EyeTrackVR/EyeTrackVR"

[tool.poetry.dependencies]
python = "~3.11.0"
python-osc = "^1.9.3"
requests = "^2.32.4"
opencv-python = "~4.11.0.86"
numpy = "~1.26.4"
pye3d = "^0.3.2"
freesimplegui = "^5.2.0.post1"
pydantic = "^2.11.7"
scikit-image = "*"
pyserial = "^3.5"
winotify = [ 
    { version = "^1.1.0", platform = 'win32' }
]
onnxruntime = "^1.22.1"
colorama = "^0.4.6"
taskipy = "^1.14.1"
pytest = "^8.4.1"
pytest-cov = "^6.2.1"
numba = "^0.61.2"
pygrabber = "^0.2"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
pyinstaller = "^6.14.2"
flake8 = "^5.0.4"

[tool.taskipy.tasks]
dev = "python eyetrackapp.py"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-ra -q"
pythonpath = "."
python_files = [
    "test_*.py"
]